- Infra:
    - Proxmox:
        icon: proxmox
        href: https://10.1.2.103:8006
        description: PVE Web UI

    - Synology NAS:
        icon: synology
        href: http://10.1.2.61:5000
        description: DSM 管理頁

    - Nginx Proxy Manager:
        icon: nginx
        href: http://npm.lan:81/
        description: 反向代理管理

- Containers:
    - Portainer:
        icon: portainer
        href: http://portainer.lan
        description: 容器管理

    - Homepage:
        icon: homepage
        href: http://home.lan
        description: Lab 首頁

    - Uptime Kuma:
        icon: uptime-kuma
        href: http://kuma.lan
        description: 監控 / 告警

    - Stirling PDF:
        icon: mdi-file-pdf-box
        href: http://pdf.lan
        description: PDF 工具

    - Docker Host (VM):
        icon: mdi-ubuntu
        href: http://10.1.2.19
        description: Ubuntu VM
